#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-insync-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-insync ]; then
	echo '** [insync] To selectively sync specific folders, enter the container and execute "manage_sync"'
	echo '** [insync] To manage your Ignored Files, enter the container and execute "manage_ignore"'
fi

NUM=`printenv | sort | grep '\INSYNC.*USERNAME' | wc -l`
    for (( i = 1; i <= $NUM; i++ ))
    do

        INSYNC_USERNAME=INSYNC${i}_USERNAME
        INSYNC_DOWNLOAD=INSYNC${i}_DOWNLOAD
        INSYNC_AUTH_CODE=INSYNC${i}_AUTH_CODE

        mkdir -p /data/${!INSYNC_USERNAME}
        echo '** [insync] Starting insync-headless for '${!INSYNC_USERNAME}
    done

sudo -u insync exec /usr/bin/insync-headless start --no-daemon
