#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="insync"
check_container_initialized
check_service_initialized init

print_info "To selectively sync specific folders, enter the container and execute 'manage_sync'"
print_info "To manage your Ignored Files, enter the container and execute 'manage_ignore'"

NUM=`printenv | sort | grep '\INSYNC.*USERNAME' | wc -l`
for (( i = 1; i <= $NUM; i++ ))
    do
    INSYNC_USERNAME=INSYNC${i}_USERNAME
    INSYNC_DOWNLOAD=INSYNC${i}_DOWNLOAD
    INSYNC_AUTH_CODE=INSYNC${i}_AUTH_CODE

    mkdir -p /data/${!INSYNC_USERNAME}
    print_start "Starting insync-headless for '${!INSYNC_USERNAME}'"
    done

liftoff
sudo -u insync exec /usr/bin/insync-headless start --no-daemon
