#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="insync"

chown -R insync: /data
sudo -u insync mkdir -p /data/.config/Insync

### Sanity Test
sanity_var INSYNC1_USERNAME "Google Drive Account"
sanity_var INSYNC1_AUTH_CODE "Authentication Code - Visit https://goo.gl/jv797S and follow the steps"

### Upgrade catcher
if [ -d "/root/.config/Insync" ]; then
  print_warn "Old version of Insync Image detected, copying files to new unified storage area. Please delete old volume mapping to `/root/.config/Insync`"
  cp -R /root/.config/Insync /data/.config/
  chown -R insync: /data/.config/Insync
fi

create_zabbix insync

### Sudo Hack for entering inside the container
echo "alias insync-headless='sudo -u insync insync-headless'" > /root/.bashrc

sudo -u insync mkdir -p /data/${INSYNC1_USERNAME}

sudo -u insync /usr/bin/insync-headless start
print_notice "Sleeping 10 seconds"
sleep 10

### Set Proxy
if [ "$PROXY_MODE" = "NONE" ] || [ "$PROXY_MODE" = "none" ] || [ "$PROXY_MODE" = "system" ] || [ "$PROXY_MODE" = "SYSTEM" ] || [ "$PROXY_MODE" = "true" ] || [ "$PROXY_MODE" = "TRUE" ];  then
  PROXY_MODE=NONE
  sudo -u insync /usr/bin/insync-headless set_proxy $PROXY_MODE
else
  echo "** [insync] Setting Proxy type to "$PROXY_MODE $PROXY_HOST" "$PROXY_PORT
  sudo -u insync /usr/bin/insync-headless set_proxy $PROXY_MODE $PROXY_TYPE $PROXY_HOST $PROXY_PORT $PROXY_USER $PROXY_PASS
fi

### Check to see if accounts are unlinked
if sudo -u insync insync-headless get_status | grep 'UNLINKED' > dev/null; then
  print_notice "Attempting to Authorize Accounts"
    NUM=`printenv | sort | grep '\INSYNC.*USERNAME' | wc -l`
    for (( i = 1; i <= $NUM; i++ ))
    do

        INSYNC_USERNAME=INSYNC${i}_USERNAME
        INSYNC_DOWNLOAD=INSYNC${i}_DOWNLOAD
        INSYNC_AUTH_CODE=INSYNC${i}_AUTH_CODE

        sudo -u insync mkdir -p /data/${!INSYNC_USERNAME}
        print_notice "Adding Account ${!INSYNC_USERNAME}"
        echo yes | sudo -u insync /usr/bin/insync-headless add_account -a ${!INSYNC_AUTH_CODE} -p /data/${!INSYNC_USERNAME} -e ${!INSYNC_DOWNLOAD}
    done
fi
sudo -u insync /usr/bin/insync-headless set_autostart yes
pkill insync-headless

custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"
custom_scripts

liftoff
