name: "manual_build_image"

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build'
        required: false

jobs:
  build:
    uses: tiredofit/github_actions/.github/workflows/default_amd64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64_armv7_arm64.yml@main
    #uses: tiredofit/github_actions/.github/workflows/default_amd64_arm64.yml@main
    secrets: inherit
